### ISSUE TITLE
node-gyp no longer in /usr/lib/sdk/node18/bin

### ISSUE THREAD

**Issue by Lunarequest** [flathub/org.freedesktop.Sdk.Extension.node18#42]
it seems at some point node-gyp was removed from `/usr/lib/sdk/node18/bin` which leads to many js libraries that have native bindings failing to build. the files for it live in `/usr/lib/sdk/node18/lib/node_modules/npm/node_modules/node-gyp/bin` but this file is a js file and can't normally be executed as most scripts expect node-gyp to be `node-gyp` and not `node-gyp.js`. I ended up making a think wrapper for github desktop like this

```yaml
- name: node-gyp
    buildsystem: simple
    build-commands:
      - install -Dm755  node-gyp /app/bin
    cleanup:
      - "*"
    sources:
      - type: script
        dest-filename: node-gyp
        commands:
          - node /usr/lib/sdk/node18/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js $@
 ```
ideally this should be part of the SDK or documented
